export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST'
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'

export const FETCH_AUTO_SUGGEST_REQUEST = 'FETCH_AUTO_SUGGEST_REQUEST'
export const FETCH_AUTO_SUGGEST_FAILURE = 'FETCH_AUTO_SUGGEST_FAILURE'
export const FETCH_AUTO_SUGGEST_SUCCESS = 'FETCH_AUTO_SUGGEST_SUCCESS'

export const BOOK_SELECT = 'BOOK_SELECT'
